name = "cfw-bun-hono"
"main" = "src/index.ts"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat_v2"]

[[d1_databases]]
 binding = "DB"
 database_name = "pwdmanager"
 database_id = "da4b9d45-f57b-475e-8c0f-6990b47c5386"

 [[d1_databases]]
binding = "DB"
database_name = "madamis-db"
database_id = "7e359530-09dd-4617-a265-cccfeea5a5f0"
preview_database_id = "DB"
# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
